### ISSUE TITLE
merge remark-man and marked-man into one project ?

### ISSUE THREAD

**Issue by kapouer** [wooorm/remark-man#5]
Hi,
i'm the maintainer of [marked-man](https://github.com/kapouer/marked-man) and
i think that our projects are so similar they should benefit from being merged into one.

What do you think ?

**Comment by wooorm** [comment]
Hey @kapouer, why would you want this?

The projects are similar in what their output but quite different in their internal workings: marked-man is named after its markdown parser, and remark-man after its markdown processor.

**Comment by wooorm** [comment]
Closed due to no response.

**Comment by kapouer** [comment]
No problem, your first answer just closed the discussion already.

**Comment by wooorm** [comment]
:+1:
